import express from 'express';
import http from 'http';
import crypto from 'crypto';
import cookieParser from 'cookie-parser';
import multer from 'multer';
import {WebSocketServer,WebSocket} from 'ws';
const API='https://discord.com/api/v10';const app=express();const server=http.createServer(app);const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});const sessions=new Map(),sockets=new Map();
app.use(express.json({limit:'2mb'}));app.use(cookieParser());app.use(express.static('.',{extensions:['html']}));
const id=()=>crypto.randomBytes(24).toString('hex');const sessionFrom=req=>req.cookies.materiacord_session?sessions.get(req.cookies.materiacord_session):null;function auth(req,res,next){const s=sessionFrom(req);if(!s)return res.status(401).json({message:'Not connected'});req.session=s;next()}
async function discordFetch(s,path,opt={}){const h=new Headers(opt.headers||{});h.set('Authorization',`Bot ${s.token}`);if(opt.body&&!(opt.body instanceof FormData)&&!h.has('Content-Type'))h.set('Content-Type','application/json');const r=await fetch(API+path,{...opt,headers:h});const t=await r.text();if(!r.ok){let m=t;try{m=JSON.parse(t).message||t}catch{}throw Error(`${r.status}: ${m}`)}return r.status===204||!t?null:JSON.parse(t)}
class Gateway{constructor(s){this.s=s;this.ws=null;this.seq=null;this.sid=null;this.timer=null;this.closed=false;this.delay=1000}async start(){await this.open(false)}async open(resume){if(this.closed)return;try{const g=await discordFetch(this.s,'/gateway/bot');this.ws=new WebSocket(g.url+'?v=10&encoding=json');this.ws.onmessage=e=>this.on(JSON.parse(e.data));this.ws.onclose=()=>{clearInterval(this.timer);if(!this.closed){const d=Math.min(this.delay,30000);this.delay=Math.min(this.delay*2,30000);setTimeout(()=>this.open(!!this.sid),d)}};this.resume=resume}catch{setTimeout(()=>this.open(!!this.sid),Math.min(this.delay,30000))}}send(op,d){if(this.ws?.readyState===WebSocket.OPEN)this.ws.send(JSON.stringify({op,d}))}broadcast(m){const set=sockets.get(this.s.id);if(!set)return;const p=JSON.stringify(m);for(const w of set)if(w.readyState===WebSocket.OPEN)w.send(p)}on(p){if(p.s!=null)this.seq=p.s;if(p.op===10){clearInterval(this.timer);this.timer=setInterval(()=>this.send(1,this.seq),p.d.heartbeat_interval);this.delay=1000;if(this.resume&&this.sid)this.send(6,{token:this.s.token,session_id:this.sid,seq:this.seq});else this.send(2,{token:this.s.token,intents:1|2|128|256|512|1024|2048|32768|4096|8192,properties:{os:'android',browser:'MateriaCord',device:'MateriaCord'}});return}if(p.op===7){this.ws?.close();return}if(p.op===9){this.sid=null;this.ws?.close();return}if(p.op===1){this.send(1,this.seq);return}if(p.op===0){if(p.t==='READY')this.sid=p.d.session_id;this.broadcast({t:p.t,d:p.d})}}stop(){this.closed=true;clearInterval(this.timer);this.ws?.close()}}
app.get('/health',(req,res)=>res.json({ok:true,name:'MateriaCord',time:new Date().toISOString()}));
app.post('/api/session',async(req,res)=>{try{const token=String(req.body?.token||'').trim();if(!token)return res.status(400).json({message:'Bot token required'});const old=sessionFrom(req);if(old){old.gateway.stop();sessions.delete(old.id);sockets.delete(old.id)}const s={id:id(),token,me:null,gateway:null};s.me=await discordFetch(s,'/users/@me');s.gateway=new Gateway(s);sessions.set(s.id,s);sockets.set(s.id,new Set());s.gateway.start();res.cookie('materiacord_session',s.id,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:43200000});res.json({me:s.me,guilds:await discordFetch(s,'/users/@me/guilds?with_counts=true')})}catch(e){res.status(400).json({message:e.message})}});
app.get('/api/session',auth,async(req,res)=>res.json({me:req.session.me,guilds:await discordFetch(req.session,'/users/@me/guilds?with_counts=true')}));app.delete('/api/session',auth,(req,res)=>{req.session.gateway.stop();sessions.delete(req.session.id);sockets.delete(req.session.id);res.clearCookie('materiacord_session');res.status(204).end()});
app.get('/api/guilds/:id/channels',auth,async(req,res)=>{try{res.json(await discordFetch(req.session,`/guilds/${req.params.id}/channels`))}catch(e){res.status(500).json({message:e.message})}});app.get('/api/channels/:id/messages',auth,async(req,res)=>{try{const n=Math.min(Math.max(Number(req.query.limit||75),1),100);let p=`/channels/${req.params.id}/messages?limit=${n}`;if(req.query.before)p+=`&before=${encodeURIComponent(req.query.before)}`;res.json(await discordFetch(req.session,p))}catch(e){res.status(500).json({message:e.message})}});
app.post('/api/channels/:id/messages',auth,upload.array('files',10),async(req,res)=>{try{const body={content:String(req.body.content||'').slice(0,2000)};if(req.body.replyTo)body.message_reference={message_id:String(req.body.replyTo),fail_if_not_exists:false};let out;if((req.files||[]).length){const f=new FormData();f.append('payload_json',JSON.stringify(body));for(const x of req.files)f.append('files[]',new Blob([x.buffer],{type:x.mimetype}),x.originalname);out=await discordFetch(req.session,`/channels/${req.params.id}/messages`,{method:'POST',body:f})}else out=await discordFetch(req.session,`/channels/${req.params.id}/messages`,{method:'POST',body:JSON.stringify(body)});res.json(out)}catch(e){res.status(500).json({message:e.message})}});
app.patch('/api/channels/:c/messages/:m',auth,async(req,res)=>{try{res.json(await discordFetch(req.session,`/channels/${req.params.c}/messages/${req.params.m}`,{method:'PATCH',body:JSON.stringify({content:String(req.body.content||'').slice(0,2000)})}))}catch(e){res.status(500).json({message:e.message})}});app.delete('/api/channels/:c/messages/:m',auth,async(req,res)=>{try{await discordFetch(req.session,`/channels/${req.params.c}/messages/${req.params.m}`,{method:'DELETE'});res.status(204).end()}catch(e){res.status(500).json({message:e.message})}});
app.put('/api/channels/:c/messages/:m/reactions/:e',auth,async(req,res)=>{try{await discordFetch(req.session,`/channels/${req.params.c}/messages/${req.params.m}/reactions/${encodeURIComponent(req.params.e)}/@me`,{method:'PUT'});res.status(204).end()}catch(e){res.status(500).json({message:e.message})}});app.post('/api/channels/:c/typing',auth,async(req,res)=>{try{await discordFetch(req.session,`/channels/${req.params.c}/typing`,{method:'POST'});res.status(204).end()}catch(e){res.status(500).json({message:e.message})}});
app.get(/.*/,(req,res)=>res.sendFile(process.cwd()+'/index.html'));
const wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,socket,head)=>{if(req.url!=='/ws'){socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});wss.on('connection',(ws,req)=>{const c=Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1).trim())]}));const s=sessions.get(c.materiacord_session);if(!s){ws.close();return}let set=sockets.get(s.id);if(!set)sockets.set(s.id,set=new Set());set.add(ws);ws.send(JSON.stringify({t:'SOCKET_READY',d:{me:s.me}}));ws.on('close',()=>set.delete(ws))});
server.listen(Number(process.env.PORT||3000),()=>console.log('MateriaCord listening on '+(process.env.PORT||3000)));
