// Copyright 2026 The BoardBridge Authors
// Licensed under the Apache License, Version 2.0.
//
// @generated by tools/generate_sdl_tables.py -- DO NOT EDIT BY HAND.
//
// Derived from SDL3 (zlib license) and Android platform headers
// (Apache-2.0). See NOTICE for attribution. Regenerate with:
//
//     python3 tools/generate_sdl_tables.py
//
// Source digests (sha256 of the upstream files this table was generated from):
//   SDL_androidkeyboard.c    07277fe0f45fe9aa3b439186f815ce861a95fabadaef218536586a9fb6963d47
//   SDL_gamepad.h            75cf6ef6d18ed6101e4f02eee99c1ec40ed21a0ef4a36f56b989972996e11fc7
//   SDL_keycode.h            398e8d68d97b1e197678401fbf900eb41860cc5bf2637fc5319779f4dee1e3a3
//   SDL_scancode.h           f99aa87627b6d5c1617046edfe51318e8f8dfde6d786da95b97a3199fe48ef24
//   input.h                  3fe3b472c1886fa8ffb21aa1391288c1138e6839b994488b4e4ac7a0ec78d803
//   keycodes.h               9fb7647c147b08e2ba7be6022be24b6a6866d1568a7b45cae51e10f5a52b5d5c

/// Android keycodes that can be translated (indices 0..N-1 of
/// [`ANDROID_KEYCODE_TO_SCANCODE`]); anything larger is unmapped and is
/// reported to the caller as `SDL_SCANCODE_UNKNOWN`.
pub const ANDROID_KEYCODE_LIMIT: usize = 280;

// ---- SDL_Scancode (SDL3, include/SDL3/SDL_scancode.h) ----

pub const SDL_SCANCODE_UNKNOWN: u16 = 0;
pub const SDL_SCANCODE_A: u16 = 4;
pub const SDL_SCANCODE_B: u16 = 5;
pub const SDL_SCANCODE_C: u16 = 6;
pub const SDL_SCANCODE_D: u16 = 7;
pub const SDL_SCANCODE_E: u16 = 8;
pub const SDL_SCANCODE_F: u16 = 9;
pub const SDL_SCANCODE_G: u16 = 10;
pub const SDL_SCANCODE_H: u16 = 11;
pub const SDL_SCANCODE_I: u16 = 12;
pub const SDL_SCANCODE_J: u16 = 13;
pub const SDL_SCANCODE_K: u16 = 14;
pub const SDL_SCANCODE_L: u16 = 15;
pub const SDL_SCANCODE_M: u16 = 16;
pub const SDL_SCANCODE_N: u16 = 17;
pub const SDL_SCANCODE_O: u16 = 18;
pub const SDL_SCANCODE_P: u16 = 19;
pub const SDL_SCANCODE_Q: u16 = 20;
pub const SDL_SCANCODE_R: u16 = 21;
pub const SDL_SCANCODE_S: u16 = 22;
pub const SDL_SCANCODE_T: u16 = 23;
pub const SDL_SCANCODE_U: u16 = 24;
pub const SDL_SCANCODE_V: u16 = 25;
pub const SDL_SCANCODE_W: u16 = 26;
pub const SDL_SCANCODE_X: u16 = 27;
pub const SDL_SCANCODE_Y: u16 = 28;
pub const SDL_SCANCODE_Z: u16 = 29;
pub const SDL_SCANCODE_1: u16 = 30;
pub const SDL_SCANCODE_2: u16 = 31;
pub const SDL_SCANCODE_3: u16 = 32;
pub const SDL_SCANCODE_4: u16 = 33;
pub const SDL_SCANCODE_5: u16 = 34;
pub const SDL_SCANCODE_6: u16 = 35;
pub const SDL_SCANCODE_7: u16 = 36;
pub const SDL_SCANCODE_8: u16 = 37;
pub const SDL_SCANCODE_9: u16 = 38;
pub const SDL_SCANCODE_0: u16 = 39;
pub const SDL_SCANCODE_RETURN: u16 = 40;
pub const SDL_SCANCODE_ESCAPE: u16 = 41;
pub const SDL_SCANCODE_BACKSPACE: u16 = 42;
pub const SDL_SCANCODE_TAB: u16 = 43;
pub const SDL_SCANCODE_SPACE: u16 = 44;
pub const SDL_SCANCODE_MINUS: u16 = 45;
pub const SDL_SCANCODE_EQUALS: u16 = 46;
pub const SDL_SCANCODE_LEFTBRACKET: u16 = 47;
pub const SDL_SCANCODE_RIGHTBRACKET: u16 = 48;
pub const SDL_SCANCODE_BACKSLASH: u16 = 49;
pub const SDL_SCANCODE_NONUSHASH: u16 = 50;
pub const SDL_SCANCODE_SEMICOLON: u16 = 51;
pub const SDL_SCANCODE_APOSTROPHE: u16 = 52;
pub const SDL_SCANCODE_GRAVE: u16 = 53;
pub const SDL_SCANCODE_COMMA: u16 = 54;
pub const SDL_SCANCODE_PERIOD: u16 = 55;
pub const SDL_SCANCODE_SLASH: u16 = 56;
pub const SDL_SCANCODE_CAPSLOCK: u16 = 57;
pub const SDL_SCANCODE_F1: u16 = 58;
pub const SDL_SCANCODE_F2: u16 = 59;
pub const SDL_SCANCODE_F3: u16 = 60;
pub const SDL_SCANCODE_F4: u16 = 61;
pub const SDL_SCANCODE_F5: u16 = 62;
pub const SDL_SCANCODE_F6: u16 = 63;
pub const SDL_SCANCODE_F7: u16 = 64;
pub const SDL_SCANCODE_F8: u16 = 65;
pub const SDL_SCANCODE_F9: u16 = 66;
pub const SDL_SCANCODE_F10: u16 = 67;
pub const SDL_SCANCODE_F11: u16 = 68;
pub const SDL_SCANCODE_F12: u16 = 69;
pub const SDL_SCANCODE_PRINTSCREEN: u16 = 70;
pub const SDL_SCANCODE_SCROLLLOCK: u16 = 71;
pub const SDL_SCANCODE_PAUSE: u16 = 72;
pub const SDL_SCANCODE_INSERT: u16 = 73;
pub const SDL_SCANCODE_HOME: u16 = 74;
pub const SDL_SCANCODE_PAGEUP: u16 = 75;
pub const SDL_SCANCODE_DELETE: u16 = 76;
pub const SDL_SCANCODE_END: u16 = 77;
pub const SDL_SCANCODE_PAGEDOWN: u16 = 78;
pub const SDL_SCANCODE_RIGHT: u16 = 79;
pub const SDL_SCANCODE_LEFT: u16 = 80;
pub const SDL_SCANCODE_DOWN: u16 = 81;
pub const SDL_SCANCODE_UP: u16 = 82;
pub const SDL_SCANCODE_NUMLOCKCLEAR: u16 = 83;
pub const SDL_SCANCODE_KP_DIVIDE: u16 = 84;
pub const SDL_SCANCODE_KP_MULTIPLY: u16 = 85;
pub const SDL_SCANCODE_KP_MINUS: u16 = 86;
pub const SDL_SCANCODE_KP_PLUS: u16 = 87;
pub const SDL_SCANCODE_KP_ENTER: u16 = 88;
pub const SDL_SCANCODE_KP_1: u16 = 89;
pub const SDL_SCANCODE_KP_2: u16 = 90;
pub const SDL_SCANCODE_KP_3: u16 = 91;
pub const SDL_SCANCODE_KP_4: u16 = 92;
pub const SDL_SCANCODE_KP_5: u16 = 93;
pub const SDL_SCANCODE_KP_6: u16 = 94;
pub const SDL_SCANCODE_KP_7: u16 = 95;
pub const SDL_SCANCODE_KP_8: u16 = 96;
pub const SDL_SCANCODE_KP_9: u16 = 97;
pub const SDL_SCANCODE_KP_0: u16 = 98;
pub const SDL_SCANCODE_KP_PERIOD: u16 = 99;
pub const SDL_SCANCODE_NONUSBACKSLASH: u16 = 100;
pub const SDL_SCANCODE_APPLICATION: u16 = 101;
pub const SDL_SCANCODE_POWER: u16 = 102;
pub const SDL_SCANCODE_KP_EQUALS: u16 = 103;
pub const SDL_SCANCODE_F13: u16 = 104;
pub const SDL_SCANCODE_F14: u16 = 105;
pub const SDL_SCANCODE_F15: u16 = 106;
pub const SDL_SCANCODE_F16: u16 = 107;
pub const SDL_SCANCODE_F17: u16 = 108;
pub const SDL_SCANCODE_F18: u16 = 109;
pub const SDL_SCANCODE_F19: u16 = 110;
pub const SDL_SCANCODE_F20: u16 = 111;
pub const SDL_SCANCODE_F21: u16 = 112;
pub const SDL_SCANCODE_F22: u16 = 113;
pub const SDL_SCANCODE_F23: u16 = 114;
pub const SDL_SCANCODE_F24: u16 = 115;
pub const SDL_SCANCODE_EXECUTE: u16 = 116;
pub const SDL_SCANCODE_HELP: u16 = 117;
pub const SDL_SCANCODE_MENU: u16 = 118;
pub const SDL_SCANCODE_SELECT: u16 = 119;
pub const SDL_SCANCODE_STOP: u16 = 120;
pub const SDL_SCANCODE_AGAIN: u16 = 121;
pub const SDL_SCANCODE_UNDO: u16 = 122;
pub const SDL_SCANCODE_CUT: u16 = 123;
pub const SDL_SCANCODE_COPY: u16 = 124;
pub const SDL_SCANCODE_PASTE: u16 = 125;
pub const SDL_SCANCODE_FIND: u16 = 126;
pub const SDL_SCANCODE_MUTE: u16 = 127;
pub const SDL_SCANCODE_VOLUMEUP: u16 = 128;
pub const SDL_SCANCODE_VOLUMEDOWN: u16 = 129;
pub const SDL_SCANCODE_KP_COMMA: u16 = 133;
pub const SDL_SCANCODE_KP_EQUALSAS400: u16 = 134;
pub const SDL_SCANCODE_INTERNATIONAL1: u16 = 135;
pub const SDL_SCANCODE_INTERNATIONAL2: u16 = 136;
pub const SDL_SCANCODE_INTERNATIONAL3: u16 = 137;
pub const SDL_SCANCODE_INTERNATIONAL4: u16 = 138;
pub const SDL_SCANCODE_INTERNATIONAL5: u16 = 139;
pub const SDL_SCANCODE_INTERNATIONAL6: u16 = 140;
pub const SDL_SCANCODE_INTERNATIONAL7: u16 = 141;
pub const SDL_SCANCODE_INTERNATIONAL8: u16 = 142;
pub const SDL_SCANCODE_INTERNATIONAL9: u16 = 143;
pub const SDL_SCANCODE_LANG1: u16 = 144;
pub const SDL_SCANCODE_LANG2: u16 = 145;
pub const SDL_SCANCODE_LANG3: u16 = 146;
pub const SDL_SCANCODE_LANG4: u16 = 147;
pub const SDL_SCANCODE_LANG5: u16 = 148;
pub const SDL_SCANCODE_LANG6: u16 = 149;
pub const SDL_SCANCODE_LANG7: u16 = 150;
pub const SDL_SCANCODE_LANG8: u16 = 151;
pub const SDL_SCANCODE_LANG9: u16 = 152;
pub const SDL_SCANCODE_ALTERASE: u16 = 153;
pub const SDL_SCANCODE_SYSREQ: u16 = 154;
pub const SDL_SCANCODE_CANCEL: u16 = 155;
pub const SDL_SCANCODE_CLEAR: u16 = 156;
pub const SDL_SCANCODE_PRIOR: u16 = 157;
pub const SDL_SCANCODE_RETURN2: u16 = 158;
pub const SDL_SCANCODE_SEPARATOR: u16 = 159;
pub const SDL_SCANCODE_OUT: u16 = 160;
pub const SDL_SCANCODE_OPER: u16 = 161;
pub const SDL_SCANCODE_CLEARAGAIN: u16 = 162;
pub const SDL_SCANCODE_CRSEL: u16 = 163;
pub const SDL_SCANCODE_EXSEL: u16 = 164;
pub const SDL_SCANCODE_FRONT: u16 = 165;
pub const SDL_SCANCODE_KP_00: u16 = 176;
pub const SDL_SCANCODE_KP_000: u16 = 177;
pub const SDL_SCANCODE_THOUSANDSSEPARATOR: u16 = 178;
pub const SDL_SCANCODE_DECIMALSEPARATOR: u16 = 179;
pub const SDL_SCANCODE_CURRENCYUNIT: u16 = 180;
pub const SDL_SCANCODE_CURRENCYSUBUNIT: u16 = 181;
pub const SDL_SCANCODE_KP_LEFTPAREN: u16 = 182;
pub const SDL_SCANCODE_KP_RIGHTPAREN: u16 = 183;
pub const SDL_SCANCODE_KP_LEFTBRACE: u16 = 184;
pub const SDL_SCANCODE_KP_RIGHTBRACE: u16 = 185;
pub const SDL_SCANCODE_KP_TAB: u16 = 186;
pub const SDL_SCANCODE_KP_BACKSPACE: u16 = 187;
pub const SDL_SCANCODE_KP_A: u16 = 188;
pub const SDL_SCANCODE_KP_B: u16 = 189;
pub const SDL_SCANCODE_KP_C: u16 = 190;
pub const SDL_SCANCODE_KP_D: u16 = 191;
pub const SDL_SCANCODE_KP_E: u16 = 192;
pub const SDL_SCANCODE_KP_F: u16 = 193;
pub const SDL_SCANCODE_KP_XOR: u16 = 194;
pub const SDL_SCANCODE_KP_POWER: u16 = 195;
pub const SDL_SCANCODE_KP_PERCENT: u16 = 196;
pub const SDL_SCANCODE_KP_LESS: u16 = 197;
pub const SDL_SCANCODE_KP_GREATER: u16 = 198;
pub const SDL_SCANCODE_KP_AMPERSAND: u16 = 199;
pub const SDL_SCANCODE_KP_DBLAMPERSAND: u16 = 200;
pub const SDL_SCANCODE_KP_VERTICALBAR: u16 = 201;
pub const SDL_SCANCODE_KP_DBLVERTICALBAR: u16 = 202;
pub const SDL_SCANCODE_KP_COLON: u16 = 203;
pub const SDL_SCANCODE_KP_HASH: u16 = 204;
pub const SDL_SCANCODE_KP_SPACE: u16 = 205;
pub const SDL_SCANCODE_KP_AT: u16 = 206;
pub const SDL_SCANCODE_KP_EXCLAM: u16 = 207;
pub const SDL_SCANCODE_KP_MEMSTORE: u16 = 208;
pub const SDL_SCANCODE_KP_MEMRECALL: u16 = 209;
pub const SDL_SCANCODE_KP_MEMCLEAR: u16 = 210;
pub const SDL_SCANCODE_KP_MEMADD: u16 = 211;
pub const SDL_SCANCODE_KP_MEMSUBTRACT: u16 = 212;
pub const SDL_SCANCODE_KP_MEMMULTIPLY: u16 = 213;
pub const SDL_SCANCODE_KP_MEMDIVIDE: u16 = 214;
pub const SDL_SCANCODE_KP_PLUSMINUS: u16 = 215;
pub const SDL_SCANCODE_KP_CLEAR: u16 = 216;
pub const SDL_SCANCODE_KP_CLEARENTRY: u16 = 217;
pub const SDL_SCANCODE_KP_BINARY: u16 = 218;
pub const SDL_SCANCODE_KP_OCTAL: u16 = 219;
pub const SDL_SCANCODE_KP_DECIMAL: u16 = 220;
pub const SDL_SCANCODE_KP_HEXADECIMAL: u16 = 221;
pub const SDL_SCANCODE_LCTRL: u16 = 224;
pub const SDL_SCANCODE_LSHIFT: u16 = 225;
pub const SDL_SCANCODE_LALT: u16 = 226;
pub const SDL_SCANCODE_LGUI: u16 = 227;
pub const SDL_SCANCODE_RCTRL: u16 = 228;
pub const SDL_SCANCODE_RSHIFT: u16 = 229;
pub const SDL_SCANCODE_RALT: u16 = 230;
pub const SDL_SCANCODE_RGUI: u16 = 231;
pub const SDL_SCANCODE_MODE: u16 = 257;
pub const SDL_SCANCODE_SLEEP: u16 = 258;
pub const SDL_SCANCODE_WAKE: u16 = 259;
pub const SDL_SCANCODE_CHANNEL_INCREMENT: u16 = 260;
pub const SDL_SCANCODE_CHANNEL_DECREMENT: u16 = 261;
pub const SDL_SCANCODE_MEDIA_PLAY: u16 = 262;
pub const SDL_SCANCODE_MEDIA_PAUSE: u16 = 263;
pub const SDL_SCANCODE_MEDIA_RECORD: u16 = 264;
pub const SDL_SCANCODE_MEDIA_FAST_FORWARD: u16 = 265;
pub const SDL_SCANCODE_MEDIA_REWIND: u16 = 266;
pub const SDL_SCANCODE_MEDIA_NEXT_TRACK: u16 = 267;
pub const SDL_SCANCODE_MEDIA_PREVIOUS_TRACK: u16 = 268;
pub const SDL_SCANCODE_MEDIA_STOP: u16 = 269;
pub const SDL_SCANCODE_MEDIA_EJECT: u16 = 270;
pub const SDL_SCANCODE_MEDIA_PLAY_PAUSE: u16 = 271;
pub const SDL_SCANCODE_MEDIA_SELECT: u16 = 272;
pub const SDL_SCANCODE_AC_NEW: u16 = 273;
pub const SDL_SCANCODE_AC_OPEN: u16 = 274;
pub const SDL_SCANCODE_AC_CLOSE: u16 = 275;
pub const SDL_SCANCODE_AC_EXIT: u16 = 276;
pub const SDL_SCANCODE_AC_SAVE: u16 = 277;
pub const SDL_SCANCODE_AC_PRINT: u16 = 278;
pub const SDL_SCANCODE_AC_PROPERTIES: u16 = 279;
pub const SDL_SCANCODE_AC_SEARCH: u16 = 280;
pub const SDL_SCANCODE_AC_HOME: u16 = 281;
pub const SDL_SCANCODE_AC_BACK: u16 = 282;
pub const SDL_SCANCODE_AC_FORWARD: u16 = 283;
pub const SDL_SCANCODE_AC_STOP: u16 = 284;
pub const SDL_SCANCODE_AC_REFRESH: u16 = 285;
pub const SDL_SCANCODE_AC_BOOKMARKS: u16 = 286;
pub const SDL_SCANCODE_SOFTLEFT: u16 = 287;
pub const SDL_SCANCODE_SOFTRIGHT: u16 = 288;
pub const SDL_SCANCODE_CALL: u16 = 289;
pub const SDL_SCANCODE_ENDCALL: u16 = 290;
pub const SDL_SCANCODE_RESERVED: u16 = 400;

/// Every `SDL_Scancode` value that has a name, for diagnostics.
pub const SDL_SCANCODE_NAMES: [(u16, &str); 249] = [
    (0, "UNKNOWN"),
    (4, "A"),
    (5, "B"),
    (6, "C"),
    (7, "D"),
    (8, "E"),
    (9, "F"),
    (10, "G"),
    (11, "H"),
    (12, "I"),
    (13, "J"),
    (14, "K"),
    (15, "L"),
    (16, "M"),
    (17, "N"),
    (18, "O"),
    (19, "P"),
    (20, "Q"),
    (21, "R"),
    (22, "S"),
    (23, "T"),
    (24, "U"),
    (25, "V"),
    (26, "W"),
    (27, "X"),
    (28, "Y"),
    (29, "Z"),
    (30, "1"),
    (31, "2"),
    (32, "3"),
    (33, "4"),
    (34, "5"),
    (35, "6"),
    (36, "7"),
    (37, "8"),
    (38, "9"),
    (39, "0"),
    (40, "RETURN"),
    (41, "ESCAPE"),
    (42, "BACKSPACE"),
    (43, "TAB"),
    (44, "SPACE"),
    (45, "MINUS"),
    (46, "EQUALS"),
    (47, "LEFTBRACKET"),
    (48, "RIGHTBRACKET"),
    (49, "BACKSLASH"),
    (50, "NONUSHASH"),
    (51, "SEMICOLON"),
    (52, "APOSTROPHE"),
    (53, "GRAVE"),
    (54, "COMMA"),
    (55, "PERIOD"),
    (56, "SLASH"),
    (57, "CAPSLOCK"),
    (58, "F1"),
    (59, "F2"),
    (60, "F3"),
    (61, "F4"),
    (62, "F5"),
    (63, "F6"),
    (64, "F7"),
    (65, "F8"),
    (66, "F9"),
    (67, "F10"),
    (68, "F11"),
    (69, "F12"),
    (70, "PRINTSCREEN"),
    (71, "SCROLLLOCK"),
    (72, "PAUSE"),
    (73, "INSERT"),
    (74, "HOME"),
    (75, "PAGEUP"),
    (76, "DELETE"),
    (77, "END"),
    (78, "PAGEDOWN"),
    (79, "RIGHT"),
    (80, "LEFT"),
    (81, "DOWN"),
    (82, "UP"),
    (83, "NUMLOCKCLEAR"),
    (84, "KP_DIVIDE"),
    (85, "KP_MULTIPLY"),
    (86, "KP_MINUS"),
    (87, "KP_PLUS"),
    (88, "KP_ENTER"),
    (89, "KP_1"),
    (90, "KP_2"),
    (91, "KP_3"),
    (92, "KP_4"),
    (93, "KP_5"),
    (94, "KP_6"),
    (95, "KP_7"),
    (96, "KP_8"),
    (97, "KP_9"),
    (98, "KP_0"),
    (99, "KP_PERIOD"),
    (100, "NONUSBACKSLASH"),
    (101, "APPLICATION"),
    (102, "POWER"),
    (103, "KP_EQUALS"),
    (104, "F13"),
    (105, "F14"),
    (106, "F15"),
    (107, "F16"),
    (108, "F17"),
    (109, "F18"),
    (110, "F19"),
    (111, "F20"),
    (112, "F21"),
    (113, "F22"),
    (114, "F23"),
    (115, "F24"),
    (116, "EXECUTE"),
    (117, "HELP"),
    (118, "MENU"),
    (119, "SELECT"),
    (120, "STOP"),
    (121, "AGAIN"),
    (122, "UNDO"),
    (123, "CUT"),
    (124, "COPY"),
    (125, "PASTE"),
    (126, "FIND"),
    (127, "MUTE"),
    (128, "VOLUMEUP"),
    (129, "VOLUMEDOWN"),
    (133, "KP_COMMA"),
    (134, "KP_EQUALSAS400"),
    (135, "INTERNATIONAL1"),
    (136, "INTERNATIONAL2"),
    (137, "INTERNATIONAL3"),
    (138, "INTERNATIONAL4"),
    (139, "INTERNATIONAL5"),
    (140, "INTERNATIONAL6"),
    (141, "INTERNATIONAL7"),
    (142, "INTERNATIONAL8"),
    (143, "INTERNATIONAL9"),
    (144, "LANG1"),
    (145, "LANG2"),
    (146, "LANG3"),
    (147, "LANG4"),
    (148, "LANG5"),
    (149, "LANG6"),
    (150, "LANG7"),
    (151, "LANG8"),
    (152, "LANG9"),
    (153, "ALTERASE"),
    (154, "SYSREQ"),
    (155, "CANCEL"),
    (156, "CLEAR"),
    (157, "PRIOR"),
    (158, "RETURN2"),
    (159, "SEPARATOR"),
    (160, "OUT"),
    (161, "OPER"),
    (162, "CLEARAGAIN"),
    (163, "CRSEL"),
    (164, "EXSEL"),
    (165, "FRONT"),
    (176, "KP_00"),
    (177, "KP_000"),
    (178, "THOUSANDSSEPARATOR"),
    (179, "DECIMALSEPARATOR"),
    (180, "CURRENCYUNIT"),
    (181, "CURRENCYSUBUNIT"),
    (182, "KP_LEFTPAREN"),
    (183, "KP_RIGHTPAREN"),
    (184, "KP_LEFTBRACE"),
    (185, "KP_RIGHTBRACE"),
    (186, "KP_TAB"),
    (187, "KP_BACKSPACE"),
    (188, "KP_A"),
    (189, "KP_B"),
    (190, "KP_C"),
    (191, "KP_D"),
    (192, "KP_E"),
    (193, "KP_F"),
    (194, "KP_XOR"),
    (195, "KP_POWER"),
    (196, "KP_PERCENT"),
    (197, "KP_LESS"),
    (198, "KP_GREATER"),
    (199, "KP_AMPERSAND"),
    (200, "KP_DBLAMPERSAND"),
    (201, "KP_VERTICALBAR"),
    (202, "KP_DBLVERTICALBAR"),
    (203, "KP_COLON"),
    (204, "KP_HASH"),
    (205, "KP_SPACE"),
    (206, "KP_AT"),
    (207, "KP_EXCLAM"),
    (208, "KP_MEMSTORE"),
    (209, "KP_MEMRECALL"),
    (210, "KP_MEMCLEAR"),
    (211, "KP_MEMADD"),
    (212, "KP_MEMSUBTRACT"),
    (213, "KP_MEMMULTIPLY"),
    (214, "KP_MEMDIVIDE"),
    (215, "KP_PLUSMINUS"),
    (216, "KP_CLEAR"),
    (217, "KP_CLEARENTRY"),
    (218, "KP_BINARY"),
    (219, "KP_OCTAL"),
    (220, "KP_DECIMAL"),
    (221, "KP_HEXADECIMAL"),
    (224, "LCTRL"),
    (225, "LSHIFT"),
    (226, "LALT"),
    (227, "LGUI"),
    (228, "RCTRL"),
    (229, "RSHIFT"),
    (230, "RALT"),
    (231, "RGUI"),
    (257, "MODE"),
    (258, "SLEEP"),
    (259, "WAKE"),
    (260, "CHANNEL_INCREMENT"),
    (261, "CHANNEL_DECREMENT"),
    (262, "MEDIA_PLAY"),
    (263, "MEDIA_PAUSE"),
    (264, "MEDIA_RECORD"),
    (265, "MEDIA_FAST_FORWARD"),
    (266, "MEDIA_REWIND"),
    (267, "MEDIA_NEXT_TRACK"),
    (268, "MEDIA_PREVIOUS_TRACK"),
    (269, "MEDIA_STOP"),
    (270, "MEDIA_EJECT"),
    (271, "MEDIA_PLAY_PAUSE"),
    (272, "MEDIA_SELECT"),
    (273, "AC_NEW"),
    (274, "AC_OPEN"),
    (275, "AC_CLOSE"),
    (276, "AC_EXIT"),
    (277, "AC_SAVE"),
    (278, "AC_PRINT"),
    (279, "AC_PROPERTIES"),
    (280, "AC_SEARCH"),
    (281, "AC_HOME"),
    (282, "AC_BACK"),
    (283, "AC_FORWARD"),
    (284, "AC_STOP"),
    (285, "AC_REFRESH"),
    (286, "AC_BOOKMARKS"),
    (287, "SOFTLEFT"),
    (288, "SOFTRIGHT"),
    (289, "CALL"),
    (290, "ENDCALL"),
    (400, "RESERVED"),
];

/// Human-readable name of a scancode, for logging.
pub fn scancode_name(scancode: u16) -> &'static str {
    match scancode {
        0 => "UNKNOWN",
        4 => "A",
        5 => "B",
        6 => "C",
        7 => "D",
        8 => "E",
        9 => "F",
        10 => "G",
        11 => "H",
        12 => "I",
        13 => "J",
        14 => "K",
        15 => "L",
        16 => "M",
        17 => "N",
        18 => "O",
        19 => "P",
        20 => "Q",
        21 => "R",
        22 => "S",
        23 => "T",
        24 => "U",
        25 => "V",
        26 => "W",
        27 => "X",
        28 => "Y",
        29 => "Z",
        30 => "1",
        31 => "2",
        32 => "3",
        33 => "4",
        34 => "5",
        35 => "6",
        36 => "7",
        37 => "8",
        38 => "9",
        39 => "0",
        40 => "RETURN",
        41 => "ESCAPE",
        42 => "BACKSPACE",
        43 => "TAB",
        44 => "SPACE",
        45 => "MINUS",
        46 => "EQUALS",
        47 => "LEFTBRACKET",
        48 => "RIGHTBRACKET",
        49 => "BACKSLASH",
        50 => "NONUSHASH",
        51 => "SEMICOLON",
        52 => "APOSTROPHE",
        53 => "GRAVE",
        54 => "COMMA",
        55 => "PERIOD",
        56 => "SLASH",
        57 => "CAPSLOCK",
        58 => "F1",
        59 => "F2",
        60 => "F3",
        61 => "F4",
        62 => "F5",
        63 => "F6",
        64 => "F7",
        65 => "F8",
        66 => "F9",
        67 => "F10",
        68 => "F11",
        69 => "F12",
        70 => "PRINTSCREEN",
        71 => "SCROLLLOCK",
        72 => "PAUSE",
        73 => "INSERT",
        74 => "HOME",
        75 => "PAGEUP",
        76 => "DELETE",
        77 => "END",
        78 => "PAGEDOWN",
        79 => "RIGHT",
        80 => "LEFT",
        81 => "DOWN",
        82 => "UP",
        83 => "NUMLOCKCLEAR",
        84 => "KP_DIVIDE",
        85 => "KP_MULTIPLY",
        86 => "KP_MINUS",
        87 => "KP_PLUS",
        88 => "KP_ENTER",
        89 => "KP_1",
        90 => "KP_2",
        91 => "KP_3",
        92 => "KP_4",
        93 => "KP_5",
        94 => "KP_6",
        95 => "KP_7",
        96 => "KP_8",
        97 => "KP_9",
        98 => "KP_0",
        99 => "KP_PERIOD",
        100 => "NONUSBACKSLASH",
        101 => "APPLICATION",
        102 => "POWER",
        103 => "KP_EQUALS",
        104 => "F13",
        105 => "F14",
        106 => "F15",
        107 => "F16",
        108 => "F17",
        109 => "F18",
        110 => "F19",
        111 => "F20",
        112 => "F21",
        113 => "F22",
        114 => "F23",
        115 => "F24",
        116 => "EXECUTE",
        117 => "HELP",
        118 => "MENU",
        119 => "SELECT",
        120 => "STOP",
        121 => "AGAIN",
        122 => "UNDO",
        123 => "CUT",
        124 => "COPY",
        125 => "PASTE",
        126 => "FIND",
        127 => "MUTE",
        128 => "VOLUMEUP",
        129 => "VOLUMEDOWN",
        133 => "KP_COMMA",
        134 => "KP_EQUALSAS400",
        135 => "INTERNATIONAL1",
        136 => "INTERNATIONAL2",
        137 => "INTERNATIONAL3",
        138 => "INTERNATIONAL4",
        139 => "INTERNATIONAL5",
        140 => "INTERNATIONAL6",
        141 => "INTERNATIONAL7",
        142 => "INTERNATIONAL8",
        143 => "INTERNATIONAL9",
        144 => "LANG1",
        145 => "LANG2",
        146 => "LANG3",
        147 => "LANG4",
        148 => "LANG5",
        149 => "LANG6",
        150 => "LANG7",
        151 => "LANG8",
        152 => "LANG9",
        153 => "ALTERASE",
        154 => "SYSREQ",
        155 => "CANCEL",
        156 => "CLEAR",
        157 => "PRIOR",
        158 => "RETURN2",
        159 => "SEPARATOR",
        160 => "OUT",
        161 => "OPER",
        162 => "CLEARAGAIN",
        163 => "CRSEL",
        164 => "EXSEL",
        165 => "FRONT",
        176 => "KP_00",
        177 => "KP_000",
        178 => "THOUSANDSSEPARATOR",
        179 => "DECIMALSEPARATOR",
        180 => "CURRENCYUNIT",
        181 => "CURRENCYSUBUNIT",
        182 => "KP_LEFTPAREN",
        183 => "KP_RIGHTPAREN",
        184 => "KP_LEFTBRACE",
        185 => "KP_RIGHTBRACE",
        186 => "KP_TAB",
        187 => "KP_BACKSPACE",
        188 => "KP_A",
        189 => "KP_B",
        190 => "KP_C",
        191 => "KP_D",
        192 => "KP_E",
        193 => "KP_F",
        194 => "KP_XOR",
        195 => "KP_POWER",
        196 => "KP_PERCENT",
        197 => "KP_LESS",
        198 => "KP_GREATER",
        199 => "KP_AMPERSAND",
        200 => "KP_DBLAMPERSAND",
        201 => "KP_VERTICALBAR",
        202 => "KP_DBLVERTICALBAR",
        203 => "KP_COLON",
        204 => "KP_HASH",
        205 => "KP_SPACE",
        206 => "KP_AT",
        207 => "KP_EXCLAM",
        208 => "KP_MEMSTORE",
        209 => "KP_MEMRECALL",
        210 => "KP_MEMCLEAR",
        211 => "KP_MEMADD",
        212 => "KP_MEMSUBTRACT",
        213 => "KP_MEMMULTIPLY",
        214 => "KP_MEMDIVIDE",
        215 => "KP_PLUSMINUS",
        216 => "KP_CLEAR",
        217 => "KP_CLEARENTRY",
        218 => "KP_BINARY",
        219 => "KP_OCTAL",
        220 => "KP_DECIMAL",
        221 => "KP_HEXADECIMAL",
        224 => "LCTRL",
        225 => "LSHIFT",
        226 => "LALT",
        227 => "LGUI",
        228 => "RCTRL",
        229 => "RSHIFT",
        230 => "RALT",
        231 => "RGUI",
        257 => "MODE",
        258 => "SLEEP",
        259 => "WAKE",
        260 => "CHANNEL_INCREMENT",
        261 => "CHANNEL_DECREMENT",
        262 => "MEDIA_PLAY",
        263 => "MEDIA_PAUSE",
        264 => "MEDIA_RECORD",
        265 => "MEDIA_FAST_FORWARD",
        266 => "MEDIA_REWIND",
        267 => "MEDIA_NEXT_TRACK",
        268 => "MEDIA_PREVIOUS_TRACK",
        269 => "MEDIA_STOP",
        270 => "MEDIA_EJECT",
        271 => "MEDIA_PLAY_PAUSE",
        272 => "MEDIA_SELECT",
        273 => "AC_NEW",
        274 => "AC_OPEN",
        275 => "AC_CLOSE",
        276 => "AC_EXIT",
        277 => "AC_SAVE",
        278 => "AC_PRINT",
        279 => "AC_PROPERTIES",
        280 => "AC_SEARCH",
        281 => "AC_HOME",
        282 => "AC_BACK",
        283 => "AC_FORWARD",
        284 => "AC_STOP",
        285 => "AC_REFRESH",
        286 => "AC_BOOKMARKS",
        287 => "SOFTLEFT",
        288 => "SOFTRIGHT",
        289 => "CALL",
        290 => "ENDCALL",
        400 => "RESERVED",
        _ => "UNKNOWN",
    }
}

// ---- Android KeyEvent keycode -> SDL_Scancode ----
//
// This is SDL3's own Android keymap (src/video/android/SDL_androidkeyboard.c).
// Using the same mapping is what makes the bridge report the same physical
// key *positions* (SDL scancodes) as a desktop SDL3 build would.

pub static ANDROID_KEYCODE_TO_SCANCODE: [u16; 280] = [
    0, // AKEYCODE_UNKNOWN -> UNKNOWN
    287, // AKEYCODE_SOFT_LEFT -> SOFTLEFT
    288, // AKEYCODE_SOFT_RIGHT -> SOFTRIGHT
    281, // AKEYCODE_HOME -> AC_HOME
    282, // AKEYCODE_BACK -> AC_BACK
    289, // AKEYCODE_CALL -> CALL
    290, // AKEYCODE_ENDCALL -> ENDCALL
    39, // AKEYCODE_0 -> 0
    30, // AKEYCODE_1 -> 1
    31, // AKEYCODE_2 -> 2
    32, // AKEYCODE_3 -> 3
    33, // AKEYCODE_4 -> 4
    34, // AKEYCODE_5 -> 5
    35, // AKEYCODE_6 -> 6
    36, // AKEYCODE_7 -> 7
    37, // AKEYCODE_8 -> 8
    38, // AKEYCODE_9 -> 9
    0, // AKEYCODE_STAR -> UNKNOWN
    0, // AKEYCODE_POUND -> UNKNOWN
    82, // AKEYCODE_DPAD_UP -> UP
    81, // AKEYCODE_DPAD_DOWN -> DOWN
    80, // AKEYCODE_DPAD_LEFT -> LEFT
    79, // AKEYCODE_DPAD_RIGHT -> RIGHT
    40, // AKEYCODE_DPAD_CENTER -> RETURN
    128, // AKEYCODE_VOLUME_UP -> VOLUMEUP
    129, // AKEYCODE_VOLUME_DOWN -> VOLUMEDOWN
    102, // AKEYCODE_POWER -> POWER
    0, // AKEYCODE_CAMERA -> UNKNOWN
    156, // AKEYCODE_CLEAR -> CLEAR
    4, // AKEYCODE_A -> A
    5, // AKEYCODE_B -> B
    6, // AKEYCODE_C -> C
    7, // AKEYCODE_D -> D
    8, // AKEYCODE_E -> E
    9, // AKEYCODE_F -> F
    10, // AKEYCODE_G -> G
    11, // AKEYCODE_H -> H
    12, // AKEYCODE_I -> I
    13, // AKEYCODE_J -> J
    14, // AKEYCODE_K -> K
    15, // AKEYCODE_L -> L
    16, // AKEYCODE_M -> M
    17, // AKEYCODE_N -> N
    18, // AKEYCODE_O -> O
    19, // AKEYCODE_P -> P
    20, // AKEYCODE_Q -> Q
    21, // AKEYCODE_R -> R
    22, // AKEYCODE_S -> S
    23, // AKEYCODE_T -> T
    24, // AKEYCODE_U -> U
    25, // AKEYCODE_V -> V
    26, // AKEYCODE_W -> W
    27, // AKEYCODE_X -> X
    28, // AKEYCODE_Y -> Y
    29, // AKEYCODE_Z -> Z
    54, // AKEYCODE_COMMA -> COMMA
    55, // AKEYCODE_PERIOD -> PERIOD
    226, // AKEYCODE_ALT_LEFT -> LALT
    230, // AKEYCODE_ALT_RIGHT -> RALT
    225, // AKEYCODE_SHIFT_LEFT -> LSHIFT
    229, // AKEYCODE_SHIFT_RIGHT -> RSHIFT
    43, // AKEYCODE_TAB -> TAB
    44, // AKEYCODE_SPACE -> SPACE
    0, // AKEYCODE_SYM -> UNKNOWN
    0, // AKEYCODE_EXPLORER -> UNKNOWN
    0, // AKEYCODE_ENVELOPE -> UNKNOWN
    40, // AKEYCODE_ENTER -> RETURN
    42, // AKEYCODE_DEL -> BACKSPACE
    53, // AKEYCODE_GRAVE -> GRAVE
    45, // AKEYCODE_MINUS -> MINUS
    46, // AKEYCODE_EQUALS -> EQUALS
    47, // AKEYCODE_LEFT_BRACKET -> LEFTBRACKET
    48, // AKEYCODE_RIGHT_BRACKET -> RIGHTBRACKET
    49, // AKEYCODE_BACKSLASH -> BACKSLASH
    51, // AKEYCODE_SEMICOLON -> SEMICOLON
    52, // AKEYCODE_APOSTROPHE -> APOSTROPHE
    56, // AKEYCODE_SLASH -> SLASH
    0, // AKEYCODE_AT -> UNKNOWN
    0, // AKEYCODE_NUM -> UNKNOWN
    0, // AKEYCODE_HEADSETHOOK -> UNKNOWN
    0, // AKEYCODE_FOCUS -> UNKNOWN
    0, // AKEYCODE_PLUS -> UNKNOWN
    118, // AKEYCODE_MENU -> MENU
    0, // AKEYCODE_NOTIFICATION -> UNKNOWN
    280, // AKEYCODE_SEARCH -> AC_SEARCH
    271, // AKEYCODE_MEDIA_PLAY_PAUSE -> MEDIA_PLAY_PAUSE
    269, // AKEYCODE_MEDIA_STOP -> MEDIA_STOP
    267, // AKEYCODE_MEDIA_NEXT -> MEDIA_NEXT_TRACK
    268, // AKEYCODE_MEDIA_PREVIOUS -> MEDIA_PREVIOUS_TRACK
    266, // AKEYCODE_MEDIA_REWIND -> MEDIA_REWIND
    265, // AKEYCODE_MEDIA_FAST_FORWARD -> MEDIA_FAST_FORWARD
    127, // AKEYCODE_MUTE -> MUTE
    75, // AKEYCODE_PAGE_UP -> PAGEUP
    78, // AKEYCODE_PAGE_DOWN -> PAGEDOWN
    0, // AKEYCODE_PICTSYMBOLS -> UNKNOWN
    0, // AKEYCODE_SWITCH_CHARSET -> UNKNOWN
    0, // AKEYCODE_BUTTON_A -> UNKNOWN
    0, // AKEYCODE_BUTTON_B -> UNKNOWN
    0, // AKEYCODE_BUTTON_C -> UNKNOWN
    0, // AKEYCODE_BUTTON_X -> UNKNOWN
    0, // AKEYCODE_BUTTON_Y -> UNKNOWN
    0, // AKEYCODE_BUTTON_Z -> UNKNOWN
    0, // AKEYCODE_BUTTON_L1 -> UNKNOWN
    0, // AKEYCODE_BUTTON_R1 -> UNKNOWN
    0, // AKEYCODE_BUTTON_L2 -> UNKNOWN
    0, // AKEYCODE_BUTTON_R2 -> UNKNOWN
    0, // AKEYCODE_BUTTON_THUMBL -> UNKNOWN
    0, // AKEYCODE_BUTTON_THUMBR -> UNKNOWN
    0, // AKEYCODE_BUTTON_START -> UNKNOWN
    0, // AKEYCODE_BUTTON_SELECT -> UNKNOWN
    0, // AKEYCODE_BUTTON_MODE -> UNKNOWN
    41, // AKEYCODE_ESCAPE -> ESCAPE
    76, // AKEYCODE_FORWARD_DEL -> DELETE
    224, // AKEYCODE_CTRL_LEFT -> LCTRL
    228, // AKEYCODE_CTRL_RIGHT -> RCTRL
    57, // AKEYCODE_CAPS_LOCK -> CAPSLOCK
    71, // AKEYCODE_SCROLL_LOCK -> SCROLLLOCK
    227, // AKEYCODE_META_LEFT -> LGUI
    231, // AKEYCODE_META_RIGHT -> RGUI
    0, // AKEYCODE_FUNCTION -> UNKNOWN
    70, // AKEYCODE_SYSRQ -> PRINTSCREEN
    72, // AKEYCODE_BREAK -> PAUSE
    74, // AKEYCODE_MOVE_HOME -> HOME
    77, // AKEYCODE_MOVE_END -> END
    73, // AKEYCODE_INSERT -> INSERT
    283, // AKEYCODE_FORWARD -> AC_FORWARD
    262, // AKEYCODE_MEDIA_PLAY -> MEDIA_PLAY
    263, // AKEYCODE_MEDIA_PAUSE -> MEDIA_PAUSE
    0, // AKEYCODE_MEDIA_CLOSE -> UNKNOWN
    270, // AKEYCODE_MEDIA_EJECT -> MEDIA_EJECT
    264, // AKEYCODE_MEDIA_RECORD -> MEDIA_RECORD
    58, // AKEYCODE_F1 -> F1
    59, // AKEYCODE_F2 -> F2
    60, // AKEYCODE_F3 -> F3
    61, // AKEYCODE_F4 -> F4
    62, // AKEYCODE_F5 -> F5
    63, // AKEYCODE_F6 -> F6
    64, // AKEYCODE_F7 -> F7
    65, // AKEYCODE_F8 -> F8
    66, // AKEYCODE_F9 -> F9
    67, // AKEYCODE_F10 -> F10
    68, // AKEYCODE_F11 -> F11
    69, // AKEYCODE_F12 -> F12
    83, // AKEYCODE_NUM_LOCK -> NUMLOCKCLEAR
    98, // AKEYCODE_NUMPAD_0 -> KP_0
    89, // AKEYCODE_NUMPAD_1 -> KP_1
    90, // AKEYCODE_NUMPAD_2 -> KP_2
    91, // AKEYCODE_NUMPAD_3 -> KP_3
    92, // AKEYCODE_NUMPAD_4 -> KP_4
    93, // AKEYCODE_NUMPAD_5 -> KP_5
    94, // AKEYCODE_NUMPAD_6 -> KP_6
    95, // AKEYCODE_NUMPAD_7 -> KP_7
    96, // AKEYCODE_NUMPAD_8 -> KP_8
    97, // AKEYCODE_NUMPAD_9 -> KP_9
    84, // AKEYCODE_NUMPAD_DIVIDE -> KP_DIVIDE
    85, // AKEYCODE_NUMPAD_MULTIPLY -> KP_MULTIPLY
    86, // AKEYCODE_NUMPAD_SUBTRACT -> KP_MINUS
    87, // AKEYCODE_NUMPAD_ADD -> KP_PLUS
    99, // AKEYCODE_NUMPAD_DOT -> KP_PERIOD
    133, // AKEYCODE_NUMPAD_COMMA -> KP_COMMA
    88, // AKEYCODE_NUMPAD_ENTER -> KP_ENTER
    103, // AKEYCODE_NUMPAD_EQUALS -> KP_EQUALS
    182, // AKEYCODE_NUMPAD_LEFT_PAREN -> KP_LEFTPAREN
    183, // AKEYCODE_NUMPAD_RIGHT_PAREN -> KP_RIGHTPAREN
    0, // AKEYCODE_VOLUME_MUTE -> UNKNOWN
    0, // AKEYCODE_INFO -> UNKNOWN
    260, // AKEYCODE_CHANNEL_UP -> CHANNEL_INCREMENT
    261, // AKEYCODE_CHANNEL_DOWN -> CHANNEL_DECREMENT
    0, // AKEYCODE_ZOOM_IN -> UNKNOWN
    0, // AKEYCODE_ZOOM_OUT -> UNKNOWN
    0, // AKEYCODE_TV -> UNKNOWN
    0, // AKEYCODE_WINDOW -> UNKNOWN
    0, // AKEYCODE_GUIDE -> UNKNOWN
    0, // AKEYCODE_DVR -> UNKNOWN
    286, // AKEYCODE_BOOKMARK -> AC_BOOKMARKS
    0, // AKEYCODE_CAPTIONS -> UNKNOWN
    0, // AKEYCODE_SETTINGS -> UNKNOWN
    0, // AKEYCODE_TV_POWER -> UNKNOWN
    0, // AKEYCODE_TV_INPUT -> UNKNOWN
    0, // AKEYCODE_STB_POWER -> UNKNOWN
    0, // AKEYCODE_STB_INPUT -> UNKNOWN
    0, // AKEYCODE_AVR_POWER -> UNKNOWN
    0, // AKEYCODE_AVR_INPUT -> UNKNOWN
    0, // AKEYCODE_PROG_RED -> UNKNOWN
    0, // AKEYCODE_PROG_GREEN -> UNKNOWN
    0, // AKEYCODE_PROG_YELLOW -> UNKNOWN
    0, // AKEYCODE_PROG_BLUE -> UNKNOWN
    0, // AKEYCODE_APP_SWITCH -> UNKNOWN
    0, // AKEYCODE_BUTTON_1 -> UNKNOWN
    0, // AKEYCODE_BUTTON_2 -> UNKNOWN
    0, // AKEYCODE_BUTTON_3 -> UNKNOWN
    0, // AKEYCODE_BUTTON_4 -> UNKNOWN
    0, // AKEYCODE_BUTTON_5 -> UNKNOWN
    0, // AKEYCODE_BUTTON_6 -> UNKNOWN
    0, // AKEYCODE_BUTTON_7 -> UNKNOWN
    0, // AKEYCODE_BUTTON_8 -> UNKNOWN
    0, // AKEYCODE_BUTTON_9 -> UNKNOWN
    0, // AKEYCODE_BUTTON_10 -> UNKNOWN
    0, // AKEYCODE_BUTTON_11 -> UNKNOWN
    0, // AKEYCODE_BUTTON_12 -> UNKNOWN
    0, // AKEYCODE_BUTTON_13 -> UNKNOWN
    0, // AKEYCODE_BUTTON_14 -> UNKNOWN
    0, // AKEYCODE_BUTTON_15 -> UNKNOWN
    0, // AKEYCODE_BUTTON_16 -> UNKNOWN
    0, // AKEYCODE_LANGUAGE_SWITCH -> UNKNOWN
    0, // AKEYCODE_MANNER_MODE -> UNKNOWN
    0, // AKEYCODE_3D_MODE -> UNKNOWN
    0, // AKEYCODE_CONTACTS -> UNKNOWN
    0, // AKEYCODE_CALENDAR -> UNKNOWN
    0, // AKEYCODE_MUSIC -> UNKNOWN
    0, // AKEYCODE_CALCULATOR -> UNKNOWN
    148, // AKEYCODE_ZENKAKU_HANKAKU -> LANG5
    0, // AKEYCODE_EISU -> UNKNOWN
    139, // AKEYCODE_MUHENKAN -> INTERNATIONAL5
    138, // AKEYCODE_HENKAN -> INTERNATIONAL4
    146, // AKEYCODE_KATAKANA_HIRAGANA -> LANG3
    137, // AKEYCODE_YEN -> INTERNATIONAL3
    0, // AKEYCODE_RO -> UNKNOWN
    0, // AKEYCODE_KANA -> UNKNOWN
    0, // AKEYCODE_ASSIST -> UNKNOWN
    0, // AKEYCODE_BRIGHTNESS_DOWN -> UNKNOWN
    0, // AKEYCODE_BRIGHTNESS_UP -> UNKNOWN
    0, // AKEYCODE_MEDIA_AUDIO_TRACK -> UNKNOWN
    258, // AKEYCODE_SLEEP -> SLEEP
    0, // AKEYCODE_WAKEUP -> UNKNOWN
    0, // AKEYCODE_PAIRING -> UNKNOWN
    0, // AKEYCODE_MEDIA_TOP_MENU -> UNKNOWN
    0, // AKEYCODE_11 -> UNKNOWN
    0, // AKEYCODE_12 -> UNKNOWN
    0, // AKEYCODE_LAST_CHANNEL -> UNKNOWN
    0, // AKEYCODE_TV_DATA_SERVICE -> UNKNOWN
    0, // AKEYCODE_VOICE_ASSIST -> UNKNOWN
    0, // AKEYCODE_TV_RADIO_SERVICE -> UNKNOWN
    0, // AKEYCODE_TV_TELETEXT -> UNKNOWN
    0, // AKEYCODE_TV_NUMBER_ENTRY -> UNKNOWN
    0, // AKEYCODE_TV_TERRESTRIAL_ANALOG -> UNKNOWN
    0, // AKEYCODE_TV_TERRESTRIAL_DIGITAL -> UNKNOWN
    0, // AKEYCODE_TV_SATELLITE -> UNKNOWN
    0, // AKEYCODE_TV_SATELLITE_BS -> UNKNOWN
    0, // AKEYCODE_TV_SATELLITE_CS -> UNKNOWN
    0, // AKEYCODE_TV_SATELLITE_SERVICE -> UNKNOWN
    0, // AKEYCODE_TV_NETWORK -> UNKNOWN
    0, // AKEYCODE_TV_ANTENNA_CABLE -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_HDMI_1 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_HDMI_2 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_HDMI_3 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_HDMI_4 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_COMPOSITE_1 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_COMPOSITE_2 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_COMPONENT_1 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_COMPONENT_2 -> UNKNOWN
    0, // AKEYCODE_TV_INPUT_VGA_1 -> UNKNOWN
    0, // AKEYCODE_TV_AUDIO_DESCRIPTION -> UNKNOWN
    0, // AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP -> UNKNOWN
    0, // AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN -> UNKNOWN
    0, // AKEYCODE_TV_ZOOM_MODE -> UNKNOWN
    0, // AKEYCODE_TV_CONTENTS_MENU -> UNKNOWN
    0, // AKEYCODE_TV_MEDIA_CONTEXT_MENU -> UNKNOWN
    0, // AKEYCODE_TV_TIMER_PROGRAMMING -> UNKNOWN
    117, // AKEYCODE_HELP -> HELP
    0, // AKEYCODE_NAVIGATE_PREVIOUS -> UNKNOWN
    0, // AKEYCODE_NAVIGATE_NEXT -> UNKNOWN
    0, // AKEYCODE_NAVIGATE_IN -> UNKNOWN
    0, // AKEYCODE_NAVIGATE_OUT -> UNKNOWN
    0, // AKEYCODE_STEM_PRIMARY -> UNKNOWN
    0, // AKEYCODE_STEM_1 -> UNKNOWN
    0, // AKEYCODE_STEM_2 -> UNKNOWN
    0, // AKEYCODE_STEM_3 -> UNKNOWN
    0, // AKEYCODE_DPAD_UP_LEFT -> UNKNOWN
    0, // AKEYCODE_DPAD_DOWN_LEFT -> UNKNOWN
    0, // AKEYCODE_DPAD_UP_RIGHT -> UNKNOWN
    0, // AKEYCODE_DPAD_DOWN_RIGHT -> UNKNOWN
    0, // AKEYCODE_MEDIA_SKIP_FORWARD -> UNKNOWN
    0, // AKEYCODE_MEDIA_SKIP_BACKWARD -> UNKNOWN
    0, // AKEYCODE_MEDIA_STEP_FORWARD -> UNKNOWN
    0, // AKEYCODE_MEDIA_STEP_BACKWARD -> UNKNOWN
    0, // AKEYCODE_SOFT_SLEEP -> UNKNOWN
    123, // AKEYCODE_CUT -> CUT
    124, // AKEYCODE_COPY -> COPY
    125, // AKEYCODE_PASTE -> PASTE
];

/// Android keycodes that SDL3 itself leaves unmapped: keys with no
/// equivalent physical key on a desktop keyboard (media keys, vendor
/// buttons, ...). They are still delivered as key events with
/// `SDL_SCANCODE_UNKNOWN` so that text input keeps working.
pub const ANDROID_KEYCODE_UNMAPPED_COUNT: usize = 134;

// ---- SDL key modifier state (SDL3, include/SDL3/SDL_keycode.h) ----

pub const SDL_KMOD_CAPS: u16 = 0x2000;
pub const SDL_KMOD_LALT: u16 = 0x0100;
pub const SDL_KMOD_LCTRL: u16 = 0x0040;
pub const SDL_KMOD_LEVEL5: u16 = 0x0004;
pub const SDL_KMOD_LGUI: u16 = 0x0400;
pub const SDL_KMOD_LSHIFT: u16 = 0x0001;
pub const SDL_KMOD_MODE: u16 = 0x4000;
pub const SDL_KMOD_NONE: u16 = 0x0000;
pub const SDL_KMOD_NUM: u16 = 0x1000;
pub const SDL_KMOD_RALT: u16 = 0x0200;
pub const SDL_KMOD_RCTRL: u16 = 0x0080;
pub const SDL_KMOD_RGUI: u16 = 0x0800;
pub const SDL_KMOD_RSHIFT: u16 = 0x0002;
pub const SDL_KMOD_SCROLL: u16 = 0x8000;
pub const SDL_KMOD_SHIFT: u16 = 0x0003;
pub const SDL_KMOD_CTRL: u16 = 0x00c0;
pub const SDL_KMOD_ALT: u16 = 0x0300;
pub const SDL_KMOD_GUI: u16 = 0x0c00;

// ---- SDL_Gamepad axes / buttons (SDL3, include/SDL3/SDL_gamepad.h) ----

pub const SDL_GAMEPAD_AXIS_INVALID: i32 = -1;
pub const SDL_GAMEPAD_AXIS_LEFTX: i32 = 0;
pub const SDL_GAMEPAD_AXIS_LEFTY: i32 = 1;
pub const SDL_GAMEPAD_AXIS_RIGHTX: i32 = 2;
pub const SDL_GAMEPAD_AXIS_RIGHTY: i32 = 3;
pub const SDL_GAMEPAD_AXIS_LEFT_TRIGGER: i32 = 4;
pub const SDL_GAMEPAD_AXIS_RIGHT_TRIGGER: i32 = 5;
pub const SDL_GAMEPAD_BUTTON_INVALID: i32 = -1;
pub const SDL_GAMEPAD_BUTTON_SOUTH: i32 = 0;
pub const SDL_GAMEPAD_BUTTON_EAST: i32 = 1;
pub const SDL_GAMEPAD_BUTTON_WEST: i32 = 2;
pub const SDL_GAMEPAD_BUTTON_NORTH: i32 = 3;
pub const SDL_GAMEPAD_BUTTON_BACK: i32 = 4;
pub const SDL_GAMEPAD_BUTTON_GUIDE: i32 = 5;
pub const SDL_GAMEPAD_BUTTON_START: i32 = 6;
pub const SDL_GAMEPAD_BUTTON_LEFT_STICK: i32 = 7;
pub const SDL_GAMEPAD_BUTTON_RIGHT_STICK: i32 = 8;
pub const SDL_GAMEPAD_BUTTON_LEFT_SHOULDER: i32 = 9;
pub const SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER: i32 = 10;
pub const SDL_GAMEPAD_BUTTON_DPAD_UP: i32 = 11;
pub const SDL_GAMEPAD_BUTTON_DPAD_DOWN: i32 = 12;
pub const SDL_GAMEPAD_BUTTON_DPAD_LEFT: i32 = 13;
pub const SDL_GAMEPAD_BUTTON_DPAD_RIGHT: i32 = 14;
pub const SDL_GAMEPAD_BUTTON_MISC1: i32 = 15;
pub const SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1: i32 = 16;
pub const SDL_GAMEPAD_BUTTON_LEFT_PADDLE1: i32 = 17;
pub const SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2: i32 = 18;
pub const SDL_GAMEPAD_BUTTON_LEFT_PADDLE2: i32 = 19;
pub const SDL_GAMEPAD_BUTTON_TOUCHPAD: i32 = 20;
pub const SDL_GAMEPAD_BUTTON_MISC2: i32 = 21;
pub const SDL_GAMEPAD_BUTTON_MISC3: i32 = 22;
pub const SDL_GAMEPAD_BUTTON_MISC4: i32 = 23;
pub const SDL_GAMEPAD_BUTTON_MISC5: i32 = 24;
pub const SDL_GAMEPAD_BUTTON_MISC6: i32 = 25;
pub const SDL_GAMEPAD_BUTTON_LABEL_UNKNOWN: i32 = 26;
pub const SDL_GAMEPAD_BUTTON_LABEL_A: i32 = 27;
pub const SDL_GAMEPAD_BUTTON_LABEL_B: i32 = 28;
pub const SDL_GAMEPAD_BUTTON_LABEL_X: i32 = 29;
pub const SDL_GAMEPAD_BUTTON_LABEL_Y: i32 = 30;
pub const SDL_GAMEPAD_BUTTON_LABEL_CROSS: i32 = 31;
pub const SDL_GAMEPAD_BUTTON_LABEL_CIRCLE: i32 = 32;
pub const SDL_GAMEPAD_BUTTON_LABEL_SQUARE: i32 = 33;

// ---- Android gamepad axes (AOSP, include/android/input.h) ----

pub const AMOTION_EVENT_AXIS_BRAKE: i32 = 23;
pub const AMOTION_EVENT_AXIS_DISTANCE: i32 = 24;
pub const AMOTION_EVENT_AXIS_GAS: i32 = 22;
pub const AMOTION_EVENT_AXIS_GENERIC_1: i32 = 32;
pub const AMOTION_EVENT_AXIS_GENERIC_10: i32 = 41;
pub const AMOTION_EVENT_AXIS_GENERIC_11: i32 = 42;
pub const AMOTION_EVENT_AXIS_GENERIC_12: i32 = 43;
pub const AMOTION_EVENT_AXIS_GENERIC_13: i32 = 44;
pub const AMOTION_EVENT_AXIS_GENERIC_14: i32 = 45;
pub const AMOTION_EVENT_AXIS_GENERIC_15: i32 = 46;
pub const AMOTION_EVENT_AXIS_GENERIC_16: i32 = 47;
pub const AMOTION_EVENT_AXIS_GENERIC_2: i32 = 33;
pub const AMOTION_EVENT_AXIS_GENERIC_3: i32 = 34;
pub const AMOTION_EVENT_AXIS_GENERIC_4: i32 = 35;
pub const AMOTION_EVENT_AXIS_GENERIC_5: i32 = 36;
pub const AMOTION_EVENT_AXIS_GENERIC_6: i32 = 37;
pub const AMOTION_EVENT_AXIS_GENERIC_7: i32 = 38;
pub const AMOTION_EVENT_AXIS_GENERIC_8: i32 = 39;
pub const AMOTION_EVENT_AXIS_GENERIC_9: i32 = 40;
pub const AMOTION_EVENT_AXIS_GESTURE_PINCH_SCALE_FACTOR: i32 = 52;
pub const AMOTION_EVENT_AXIS_GESTURE_SCROLL_X_DISTANCE: i32 = 50;
pub const AMOTION_EVENT_AXIS_GESTURE_SCROLL_Y_DISTANCE: i32 = 51;
pub const AMOTION_EVENT_AXIS_GESTURE_SWIPE_FINGER_COUNT: i32 = 53;
pub const AMOTION_EVENT_AXIS_GESTURE_X_OFFSET: i32 = 48;
pub const AMOTION_EVENT_AXIS_GESTURE_Y_OFFSET: i32 = 49;
pub const AMOTION_EVENT_AXIS_HAT_X: i32 = 15;
pub const AMOTION_EVENT_AXIS_HAT_Y: i32 = 16;
pub const AMOTION_EVENT_AXIS_HSCROLL: i32 = 10;
pub const AMOTION_EVENT_AXIS_LTRIGGER: i32 = 17;
pub const AMOTION_EVENT_AXIS_ORIENTATION: i32 = 8;
pub const AMOTION_EVENT_AXIS_PRESSURE: i32 = 2;
pub const AMOTION_EVENT_AXIS_RELATIVE_X: i32 = 27;
pub const AMOTION_EVENT_AXIS_RELATIVE_Y: i32 = 28;
pub const AMOTION_EVENT_AXIS_RTRIGGER: i32 = 18;
pub const AMOTION_EVENT_AXIS_RUDDER: i32 = 20;
pub const AMOTION_EVENT_AXIS_RX: i32 = 12;
pub const AMOTION_EVENT_AXIS_RY: i32 = 13;
pub const AMOTION_EVENT_AXIS_RZ: i32 = 14;
pub const AMOTION_EVENT_AXIS_SCROLL: i32 = 26;
pub const AMOTION_EVENT_AXIS_SIZE: i32 = 3;
pub const AMOTION_EVENT_AXIS_THROTTLE: i32 = 19;
pub const AMOTION_EVENT_AXIS_TILT: i32 = 25;
pub const AMOTION_EVENT_AXIS_TOOL_MAJOR: i32 = 6;
pub const AMOTION_EVENT_AXIS_TOOL_MINOR: i32 = 7;
pub const AMOTION_EVENT_AXIS_TOUCH_MAJOR: i32 = 4;
pub const AMOTION_EVENT_AXIS_TOUCH_MINOR: i32 = 5;
pub const AMOTION_EVENT_AXIS_VSCROLL: i32 = 9;
pub const AMOTION_EVENT_AXIS_WHEEL: i32 = 21;
pub const AMOTION_EVENT_AXIS_X: i32 = 0;
pub const AMOTION_EVENT_AXIS_Y: i32 = 1;
pub const AMOTION_EVENT_AXIS_Z: i32 = 11;

/// Translates an Android joystick axis id into an SDL_Gamepad axis.
///
/// Android reports gamepad sticks/triggers through `AMOTION_EVENT_AXIS_*`
/// ids; SDL uses a small fixed set of `SDL_GAMEPAD_AXIS_*` axes. The HAT
/// axes are folded onto the left stick because SDL exposes the d-pad as
/// buttons, not axes.
pub fn gamepad_axis_from_android(android_axis: i32) -> Option<i32> {
    match android_axis {
        AMOTION_EVENT_AXIS_X => Some(SDL_GAMEPAD_AXIS_LEFTX),
        AMOTION_EVENT_AXIS_Y => Some(SDL_GAMEPAD_AXIS_LEFTY),
        AMOTION_EVENT_AXIS_Z => Some(SDL_GAMEPAD_AXIS_RIGHTX),
        AMOTION_EVENT_AXIS_RZ => Some(SDL_GAMEPAD_AXIS_RIGHTY),
        AMOTION_EVENT_AXIS_LTRIGGER => Some(SDL_GAMEPAD_AXIS_LEFT_TRIGGER),
        AMOTION_EVENT_AXIS_RTRIGGER => Some(SDL_GAMEPAD_AXIS_RIGHT_TRIGGER),
        AMOTION_EVENT_AXIS_HAT_X => Some(SDL_GAMEPAD_AXIS_LEFTX),
        AMOTION_EVENT_AXIS_HAT_Y => Some(SDL_GAMEPAD_AXIS_LEFTY),
        _ => None,
    }
}

/// Translates an Android gamepad button keycode (`AKEYCODE_BUTTON_*`) into
/// an SDL_Gamepad button. Android reports L2/R2 as buttons *and* as the
/// LTRIGGER/RTRIGGER axes; SDL models them as axes only, so those two
/// report `None` here and arrive through [`gamepad_axis_from_android`].
pub fn gamepad_button_from_android_keycode(keycode: i32) -> Option<i32> {
    match keycode {
        96 => Some(SDL_GAMEPAD_BUTTON_SOUTH), // AKEYCODE_BUTTON_A
        97 => Some(SDL_GAMEPAD_BUTTON_EAST), // AKEYCODE_BUTTON_B
        99 => Some(SDL_GAMEPAD_BUTTON_WEST), // AKEYCODE_BUTTON_X
        100 => Some(SDL_GAMEPAD_BUTTON_NORTH), // AKEYCODE_BUTTON_Y
        102 => Some(SDL_GAMEPAD_BUTTON_LEFT_SHOULDER), // AKEYCODE_BUTTON_L1
        103 => Some(SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER), // AKEYCODE_BUTTON_R1
        106 => Some(SDL_GAMEPAD_BUTTON_LEFT_STICK), // AKEYCODE_BUTTON_THUMBL
        107 => Some(SDL_GAMEPAD_BUTTON_RIGHT_STICK), // AKEYCODE_BUTTON_THUMBR
        108 => Some(SDL_GAMEPAD_BUTTON_START), // AKEYCODE_BUTTON_START
        109 => Some(SDL_GAMEPAD_BUTTON_BACK), // AKEYCODE_BUTTON_SELECT
        110 => Some(SDL_GAMEPAD_BUTTON_GUIDE), // AKEYCODE_BUTTON_MODE
        188 => Some(SDL_GAMEPAD_BUTTON_MISC1), // AKEYCODE_BUTTON_1
        189 => Some(SDL_GAMEPAD_BUTTON_MISC2), // AKEYCODE_BUTTON_2
        190 => Some(SDL_GAMEPAD_BUTTON_MISC3), // AKEYCODE_BUTTON_3
        191 => Some(SDL_GAMEPAD_BUTTON_MISC4), // AKEYCODE_BUTTON_4
        192 => Some(SDL_GAMEPAD_BUTTON_MISC5), // AKEYCODE_BUTTON_5
        193 => Some(SDL_GAMEPAD_BUTTON_MISC6), // AKEYCODE_BUTTON_6
        _ => None,
    }
}

